- name: configure backend server
  hosts: frontend
  become: yes
  tasks:
  - name: install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: installed

  - name: enable and star nginx 
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes

          